# Generated by Django 3.1.5 on 2022-05-03 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.CharField(max_length=300)),
                ('enquiry_replay', models.CharField(max_length=300)),
                ('status', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(default='', max_length=300)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('post_date', models.DateField(blank=True, null=True)),
                ('replay_date', models.DateField(blank=True, null=True)),
                ('feedback', models.CharField(max_length=300)),
                ('feedback_replay', models.CharField(max_length=300)),
                ('replay_status', models.CharField(default='0', max_length=20)),
                ('work_status', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('regdate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='0', max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
                ('experience', models.CharField(default='0', max_length=20)),
                ('work_name', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='designation',
        ),
        migrations.RenameModel(
            old_name='department',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='candidates',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='user_register',
            name='category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep', to='my_app.category'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='category_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='my_app.category'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid', to='my_app.user_register'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='work_name',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrkname', to='my_app.user_register'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='work_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktyp', to='my_app.user_register'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='worker_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker1', to='my_app.user_register'),
        ),
    ]
