# Generated by Django 3.1.5 on 2022-04-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='exam_status',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
