# Generated by Django 3.1.5 on 2022-05-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220504_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='user_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useride', to='my_app.user_register'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='worker_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker1e', to='my_app.user_register'),
        ),
    ]
