# Generated by Django 3.1.5 on 2022-04-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_candidates_exam_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidates',
            old_name='exam_status',
            new_name='status',
        ),
    ]
