# Generated by Django 3.1.5 on 2022-04-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220428_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='worker_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker1', to='my_app.user_register'),
        ),
    ]
