# Generated by Django 3.1.5 on 2022-04-27 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_feedback_worker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='worker_id',
        ),
    ]
