# Generated by Django 3.1.5 on 2022-04-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20220426_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('regdate', models.DateField(default='')),
                ('status', models.CharField(default='0', max_length=20)),
                ('photo', models.FileField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='department',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='candidates',
        ),
        migrations.AddField(
            model_name='user_register',
            name='deptmnt',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dep', to='my_app.category'),
        ),
    ]
