# Generated by Django 3.1.5 on 2022-04-27 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_feedback_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='worker_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker1', to='my_app.user_register'),
        ),
    ]
