# Generated by Django 3.1.5 on 2022-05-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20220504_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='work_name',
        ),
    ]
