# Generated by Django 3.1.5 on 2022-05-03 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_feedback_work_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='category_id',
        ),
    ]
