# Generated by Django 3.1.5 on 2022-04-27 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20220427_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='work_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(default='', max_length=200)),
                ('work_details', models.CharField(max_length=300)),
                ('work_status', models.CharField(default='0', max_length=20)),
                ('category_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_dep', to='my_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='work_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='login',
            name='designation',
        ),
        migrations.DeleteModel(
            name='designation',
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='work_details',
            name='work_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desgn', to='my_app.work_type'),
        ),
    ]
