# Generated by Django 3.1.5 on 2022-04-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20220427_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_details',
            name='worker_id',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_id', to='my_app.user_register'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=200)),
                ('post_date', models.CharField(default='', max_length=200)),
                ('feedback_replay', models.CharField(max_length=300)),
                ('replay_status', models.CharField(default='0', max_length=20)),
                ('category_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_deptment', to='my_app.category')),
                ('work_type', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worktyp', to='my_app.work_type')),
            ],
        ),
    ]
