# Generated by Django 3.1.5 on 2022-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_feedback_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='w_r_status',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
