# Generated by Django 3.1.5 on 2022-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20220428_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(default=3, max_length=300),
            preserve_default=False,
        ),
    ]
