# Generated by Django 3.1.5 on 2022-04-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_feedback_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='category_id',
        ),
    ]
