# Generated by Django 3.1.5 on 2022-04-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_remove_feedback_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_details',
            name='experience',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
